import graphMateKT.examples.Day7Laboratories2025
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class TestDay7Laboritories2025{
    val input = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
    """.trimIndent().lines()

    @Test
    fun test1() {
        val ans = Day7Laboratories2025(input)
        assertThat(ans).isEqualTo(40)
    }
}
