name: Kotlin CI with Maven
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # A popular, free, and open-source distribution of OpenJDK
          cache: 'maven' # Caches Maven dependencies to speed up future builds.

      - name: Run tests with Maven in batch mode
        run: mvn -B test
